language: node_js
node_js:
  - 14

cache:
  directories:
    - React/app/node_modules

branches:
  only:
    - deploy-react

before_install:
  - if [ "$TRAVIS_BRANCH" == "deploy-react" ]; then cd ./React/app; fi

before_script:
  - if [ "$TRAVIS_BRANCH" == "deploy-react" ]; then npm run build; fi

script:
  - npm publish --access=public dist; fi