version: 2.1

defaults: &defaults
  working_directory: ~/Komponent/React/app
  docker:
    - image: cimg/node:14.20.0

jobs:
  react-publish:
    <<: *defaults
    steps:
      - checkout:
          path: ~/Komponent

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies
      
      - run:
          name: install node_modules
          command: npm install
      
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ "package.json" }}
      
      - run:
          name: npm build
          environment:
            NODE_ENV: product
          command: npm run build

      - run:
          name: authentication
          command: npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN

      - run:
          name: deploy
          command: npm publish --access=public dist
  
  storybook-publish:
    <<: *defaults
    steps:
      - checkout:
          path: ~/Komponent

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies
      
      - run:
          name: install node_modules
          command: npm install
      
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ "package.json" }}
      
      - run:
          name: npm build
          environment:
            NODE_ENV: product
          command: npm run build-storybook
      
      - run:
          name: deploy
          command: npx chromatic --project-token=$CHROMATIC_TOKEN -d storybook-static

workflows:
  version: 2
  build:
    jobs:
      - react-publish:
          filters:
            branches:
              only: deploy-react
      - storybook-publish:
          filters:
            branches:
              only: deploy-storybook
